import { useRef, useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';

import { useDispatch } from 'react-redux';
import { setCredentials } from '../../Features/auth/authSlice';
import { useLazyGetUserLocationsQuery } from '../../Features/locations/locationsApiSlice';
import { useLoginMutation } from '../../Features/auth/authApiSlice';
import { setTheme, setTempUnit } from '../../Features/user_preferences/preferenceSlice';
import { setUserLocations } from '../../Features/locations/locationsSlice';

import '../../Styles/login.css';
import '../../Styles/app.css';
import formatLocation from '../../data/utils/formatLocation';
import Loading from '../Atoms/Loading';


const Login = () => {
    const userRef = useRef();
    const errRef = useRef();
    const [user, setUser] = useState('');
    const [pwd, setPwd] = useState('');
    const [errMsg, setErrMsg] = useState('');
    const navigate = useNavigate();

    //login is the trigger function for the mutation hook
    //for more info on the return of useLoginMutation(): 
    //https://redux-toolkit.zjs.org/rtk-query/usage/mutations#frequently-used-mutation-hook-return-values
    //(remember useLoginMutation is auto generated by RTK Query from 'login' endpoint)
    const [login, { isLoading }] = useLoginMutation();
    const dispatch = useDispatch();

    //useLazyQuery hook allows manual fetching
    const [triggerGetLocations] = useLazyGetUserLocationsQuery();

    useEffect(() => {
        userRef.current.focus();
    }, [])

    useEffect(() => {
        setErrMsg('');
    }, [user, pwd])

    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            //send request to backend to see if user has correct credentials
            const userData = await login({ 'username': user, 'password': pwd }).unwrap();

            const accessToken = userData.access_token;
            const csrfAccessToken = userData.csrf_access_token;

            //set application logic
            dispatch(setCredentials({ user, accessToken, csrfAccessToken }));

            //fetch user prefs if they exist
            const tempUnit = localStorage.getItem("temperatureUnit");
            const theme = localStorage.getItem("theme");
            if (tempUnit === 'Celcius' || tempUnit === 'Fahrenheit') {
                dispatch(setTempUnit({ "unit": tempUnit }));
            }
            if (theme === "Light" || theme === "Dark") {
                dispatch(setTheme({ "theme": theme }));
            }

            //get user locations from backend
            //and set user locations for application logic
            const payload = await triggerGetLocations({ 'username': user }, false).unwrap();
            const locationsFormattedCorrectly = [];
            payload?.locations.forEach(location => locationsFormattedCorrectly.push(formatLocation(location)));
            dispatch(setUserLocations({ "locations": locationsFormattedCorrectly }));

            //reset page logic (not sure if neccesary?)
            setUser('');
            setPwd('');

            //once locations are set, navigate to location page
            navigate('/locations')

        }
        catch (err) {
            console.log(err);
            if (err?.data?.message) {
                setErrMsg(err.data.message);
            } else {
                setErrMsg('No server response.');
            }
            errRef.current.focus();
        }
    }

    const handleUserInput = (e) => setUser(e.target.value);
    const handlePwdInput = (e) => setPwd(e.target.value);

    const content = isLoading ? <div className='flex-center-align'><Loading width={96} height={96} /></div> : (
        <section className='login'>
            <p ref={errRef} className={errMsg !== '' ? "errmsg" : "offscreen"}> {errMsg}</p>

            <h1>Login</h1>

            <form className='loginForm' onSubmit={handleSubmit}>
                <label htmlFor='username'>Username:</label>
                <input
                    type="text"
                    id="username"
                    ref={userRef}
                    value={user}
                    onChange={handleUserInput}
                    autoComplete="off"
                    required
                />
                <label htmlFor='password'>Password:</label>
                <input
                    type="password"
                    id="password"
                    onChange={handlePwdInput}
                    value={pwd}
                    required
                />
                <button>Sign In</button>
            </form>
            <span>Dont have an account? <Link to='/register'>Register now.</Link></span>
        </section>
    )

    return content;
}

export default Login;